### ISSUE TITLE
API method to get service log 

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/sense-o-py-client#10]
This tracks the sub task 2f of #1. Service log is service instance specific. 

* [ ] 2f. Service logging (default == all, opt: logging level + filters)
   * JSON formatted
   * support the same filters as in UI if possible. Minimum requirement is by logging level and datetime range.
   * Future -- `HTTP Stream` for logging in progress

**Comment by R-Jimenez** [comment]
This technically currently exists, it just uses query parameters which may not be too pretty. By JSON formatted I'm starting to think you mean this for both input and output, however GET requests are discouraged from having bodies (such as a JSON payload). For ex the below (url decoded): 
```https://dev1.virnao.com:8443/StackV-web/restapi/logging/logs/62e18ace-ef72-41a1-89a1-bb85fbbdde28?take=30&skip=90&sort=[{"selector":"timestamp","desc":true}]&filter=["event","contains","Verify"]```

Will get you the fourth page of 30 logs for instance `62e18ace-ef72-41a1-89a1-bb85fbbdde28`, sorting by time and filtering events for the term `Verify`. 

This may be an issue more for documentation of the current API than implementation, however in the future streaming would be extremely useful to counteract some of the large filtering overhead we have.

**Comment by xi-yang** [comment]
How about authorization policy on the logging endpoint? Can a regular user access logging outside of instances he/she was entitled to?

**Comment by R-Jimenez** [comment]
Currently there is no access control on the logging resource, but can certainly add it. It'll be good to uplift the delegation/access control code to be more accessible to other resources so this would take care of two potential issues at once.

**Comment by R-Jimenez** [comment]
Back onto logging work. Again as above I can reuse the existing endpoint if you'd want and simply document the fields, or create a separate one for client access with more restricted options. The log retrieval itself is abstracted to the handler so both endpoints can use the same retrieval function, there is just some room for improvement here since the client won't be tied to the input and structural requirements of the DataTables.

Additionally I will be adding a constraint with the new generalized AccessCheck whenever instance logs are requested.
